In [1]:
import numpy as np
import pandas as pd

In [16]:
df=pd.read_csv(r'anime.csv')
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [13]:
# Make a new column for episode count
def extract_Episode(txt):
    check = False
    data = ""
    for i in txt:
        if i == ")":
            check =False
            return data
        if check == True:
            data += i
        if i == "(":
            check =True

In [19]:
df["Episodes"] = df["Title"].apply(extract_Episode)
df['Episodes']=df['Episodes'].str.replace('eps',"")
df['Episodes']=df['Episodes'].astype(int)
df['Title'][0]

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [18]:
# make a new column for time stamps
def extraction_time(txt):
    check =False;
    data=""
    for i in range(len(txt)):
        if txt[i] == ")":
            for j in range(i+1,i+20):
                data += txt[j]
            return data
df["Total Time"]=df['Title'].apply(extraction_time)  
df.head()

,Rank,Title,Score,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,Apr 2019 - Jul 2019

In [6]:
# extracting months
from dateutil.relativedelta import relativedelta
from datetime import datetime

def calculate_total_months(period):
    try:
        start_str,end_str = period.split(' - ')
        start_date = datetime.strptime(start_str,"%b %Y")
        end_date = datetime.strptime(end_str,"%b %Y")
        r = relativedelta(end_date,start_date)
        return r.years* 12+ r.months + 1 # +1 to include the starting months
    except:
        return None

df["Months"]= df['Total Time'].apply(calculate_total_months)  
df.head()

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [7]:
# which anime has the highest score;

df[df['Score'] == df['Score'].max()]['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: object

In [8]:
# give me the top 5 highest scoring anime;
top_5_anime = df.sort_values(by='Score', ascending=False)['Title'].iloc[0:5]

# Method 2: Using direct indexing
top_5_anime = df.sort_values(by='Score', ascending=False)['Title'][0:5]

# Method 3: Using nlargest (if you specifically want top N by a numeric column)
top_5_anime = df.nlargest(5, 'Score')['Title']
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

In [9]:
# which anime has the highest episode count;
df[df['Episodes']== df['Episodes'].max()]

,Rank,Title,Score,Episodes,Total Time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

In [10]:
# anime with top 5 episodes count

df.nlargest(5,'Episodes')['Title']

15    GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...
7     Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...
11    Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
42    Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...
24    MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...
Name: Title, dtype: object

In [11]:
# which is the longest running anime

df[df['Months']== df['Months'].max()]

,Rank,Title,Score,Episodes,Total Time,Months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111