In [83]:
# create dataframes.....
import numpy as np
import pandas as pd

In [84]:
# creatind d data frames;

data ={
    'Name':["John","Anna","Peter","Linda"],
    "Age":[28,34,29,42],
    "City":["New York","paris","Berlin","London"],
    "Salary":[65000,70000,62000,85000]
}
pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [85]:
# creting data frames using list

data_list =[
    ['john',28,'Newyork',65000],
    ['anna',34,'Newyork',80000],
    ['peter',29,'Newyork',75000],
    ['Linda',42,'Newyork',45000],
    
]
df2 = pd.DataFrame(data_list)
columns = ["name","age","city",'salary']
# if the headers is missing and you want to  add then add columns
df2 = pd.DataFrame(data_list,columns=columns)
df2

    name  age     city  salary
0   john   28  Newyork   65000
1   anna   34  Newyork   80000
2  peter   29  Newyork   75000
3  Linda   42  Newyork   45000

In [86]:
# selection and indexing of columns;
df2
# if you want to indexing then numbers will not work you have to write the key
df2["name"]
# if you want to target two columns at a time
df2[["name","city","age"]]

    name     city  age
0   john  Newyork   28
1   anna  Newyork   34
2  peter  Newyork   29
3  Linda  Newyork   42

In [87]:
# creating a new column
df2["designation"] = ['Doctor',"Eng.","Doctor","carpenter"]
df2

    name  age     city  salary designation
0   john   28  Newyork   65000      Doctor
1   anna   34  Newyork   80000        Eng.
2  peter   29  Newyork   75000      Doctor
3  Linda   42  Newyork   45000   carpenter

In [88]:
# removing column
# df2.drop("designation",axis=1)
# drop data cannot delete data permanently
df2

    name  age     city  salary designation
0   john   28  Newyork   65000      Doctor
1   anna   34  Newyork   80000        Eng.
2  peter   29  Newyork   75000      Doctor
3  Linda   42  Newyork   45000   carpenter

In [89]:
# for removing data permanently
df2.drop('designation', axis=1, inplace=True)
df2

    name  age     city  salary
0   john   28  Newyork   65000
1   anna   34  Newyork   80000
2  peter   29  Newyork   75000
3  Linda   42  Newyork   45000

# Assistant
The error occurs because the column 'designation' does not exist in your DataFrame df2. When you try to drop a column that doesn't exist, pandas raises a KeyError.

Would you like me to provide the corrected code?

In [90]:
# selecting rows
df2.loc[[0,1]]

   name  age     city  salary
0  john   28  Newyork   65000
1  anna   34  Newyork   80000

In [91]:
# selecting rows
df2

    name  age     city  salary
0   john   28  Newyork   65000
1   anna   34  Newyork   80000
2  peter   29  Newyork   75000
3  Linda   42  Newyork   45000

In [92]:
# selecting subset of rows and columns
df2.loc[[2,3]][["city","salary"]]

      city  salary
2  Newyork   75000
3  Newyork   45000

In [93]:
# conditional selection <>= != etc
# select only people whose age is above30
df2[df2["age"]>30]

    name  age     city  salary
1   anna   34  Newyork   80000
3  Linda   42  Newyork   45000

In [96]:
# i only want people whose age is above 30 and their city must be paris
df2[(df2["age"]>40) & (df2["city"]=="Newyork")]

    name  age     city  salary
3  Linda   42  Newyork   45000