In [2]:
import numpy as np
import pandas as pd

In [3]:
data ={
    "A":[1,2,np.nan,4,5],
    "B":[np.nan,2,3,4,5],
    "C":[1,2,3,np.nan,np.nan],
    "D":[1,np.nan,np.nan,np.nan,5],
}
df=pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [4]:
# below line shows how many nanvalue in data and it gives answer like column wise
df.isna()
# below value gives the sum of all the nan value in columns
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [5]:
# this will give the ansewer if any value in data columns is not presenting nan vlaue
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [6]:

df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [7]:
# removeing missing data
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [8]:
# drop threshold function
df
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [9]:
# filling the missing data
# this is not gonna permanently change the data if you want to then use (inplace= truee)
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [10]:
# can fill value in specific column in specific value;
values = {"A":0,"B":100,"C":300,"D":400}
df.fillna(value=values)

     A      B      C      D
0  1.0  100.0    1.0    1.0
1  2.0    2.0    2.0  400.0
2  0.0    3.0    3.0  400.0
3  4.0    4.0  300.0  400.0
4  5.0    5.0  300.0    5.0

In [11]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [12]:
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0